name: wb_dart
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: sainath <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'


#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  intl: ^0.15.7

executables:
  addT: wb_AddTask
  updatedTask: wb_UpdateTasks
  wb_server: server