name: wb_dart
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: sainath <email@example.com>

environment:
  sdk: '>=2.1.2 <3.0.0'


dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  intl: ^0.15.7
  angular_test: ^2.2.0

executables:
  addT: wb_AddTask
  updatedTask: wb_UpdateTasks
  wb_server: server